export type FinancialItem = {
  title: string;
  category: string;
  type: "revenue" | "cost";
  value: number;
  frequency: "monthly" | "one_time" | "yearly";
  startsAt: number;
  endsAt?: number | null;
};

export type Template = {
  id: string;
  title: string;
  description: string;
  items: FinancialItem[];
};

const nowIndex = 0; // current period index

export const templates: Template[] = [
  {
    id: "1",
    title: "Early Stage SaaS Startup",
    description: "Bootstrap SaaS with initial team and product development",
    items: [
      {
        title: "Founder Salary",
        category: "Operations",
        type: "cost",
        value: 8000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Senior Engineer",
        category: "Engineering",
        type: "cost",
        value: 12000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Cloud Infrastructure",
        category: "Infrastructure",
        type: "cost",
        value: 500,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Software Tools",
        category: "Operations",
        type: "cost",
        value: 300,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Initial MRR",
        category: "Subscription",
        type: "revenue",
        value: 5000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
    ],
  },
  {
    id: "2",
    title: "Series A Growth Phase",
    description: "Post-funding expansion with sales and engineering teams",
    items: [
      {
        title: "Sales Team (3 reps)",
        category: "Sales",
        type: "cost",
        value: 45000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Engineering Team (5 engineers)",
        category: "Engineering",
        type: "cost",
        value: 75000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Marketing Lead",
        category: "Marketing",
        type: "cost",
        value: 15000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Marketing Budget",
        category: "Marketing",
        type: "cost",
        value: 25000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "ARR Growth",
        category: "Subscription",
        type: "revenue",
        value: 150000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
    ],
  },
  {
    id: "3",
    title: "Product Launch Campaign",
    description: "New product launch with marketing and sales push",
    items: [
      {
        title: "Product Marketing",
        category: "Marketing",
        type: "cost",
        value: 40000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "PR & Events",
        category: "Marketing",
        type: "cost",
        value: 15000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Sales Commission",
        category: "Sales",
        type: "cost",
        value: 20000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Launch Revenue",
        category: "Sales",
        type: "revenue",
        value: 120000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
    ],
  },
  {
    id: "4",
    title: "Office Expansion",
    description: "New office setup with one-time and recurring costs",
    items: [
      {
        title: "Office Lease",
        category: "Infrastructure",
        type: "cost",
        value: 15000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Office Furniture",
        category: "Infrastructure",
        type: "cost",
        value: 75000,
        frequency: "one_time",
        startsAt: nowIndex,
      },
      {
        title: "IT Equipment",
        category: "Infrastructure",
        type: "cost",
        value: 50000,
        frequency: "one_time",
        startsAt: nowIndex,
      },
      {
        title: "Utilities & Maintenance",
        category: "Operations",
        type: "cost",
        value: 2000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
    ],
  },
  {
    id: "5",
    title: "Enterprise Sales Team",
    description: "Build dedicated enterprise sales organization",
    items: [
      {
        title: "VP of Sales",
        category: "Sales",
        type: "cost",
        value: 20000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Enterprise AEs (3)",
        category: "Sales",
        type: "cost",
        value: 60000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Sales Development Reps (2)",
        category: "Sales",
        type: "cost",
        value: 12000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Sales Tools & CRM",
        category: "Operations",
        type: "cost",
        value: 5000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Enterprise Revenue",
        category: "Sales",
        type: "revenue",
        value: 300000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
    ],
  },
  {
    id: "6",
    title: "Customer Success Team",
    description: "Scale customer success to reduce churn and upsell",
    items: [
      {
        title: "Customer Success Manager",
        category: "Operations",
        type: "cost",
        value: 10000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Support Team (2)",
        category: "Operations",
        type: "cost",
        value: 12000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Support Tools",
        category: "Operations",
        type: "cost",
        value: 2000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Upsell Revenue",
        category: "Sales",
        type: "revenue",
        value: 40000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
    ],
  },
  {
    id: "7",
    title: "International Expansion",
    description: "Enter new markets with localized team and operations",
    items: [
      {
        title: "Regional Manager",
        category: "Operations",
        type: "cost",
        value: 15000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Local Sales Team",
        category: "Sales",
        type: "cost",
        value: 30000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Legal & Compliance",
        category: "Operations",
        type: "cost",
        value: 10000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Market Entry Costs",
        category: "Operations",
        type: "cost",
        value: 100000,
        frequency: "one_time",
        startsAt: nowIndex,
      },
      {
        title: "International Revenue",
        category: "Sales",
        type: "revenue",
        value: 80000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
    ],
  },
  {
    id: "8",
    title: "R&D Investment",
    description: "Invest in research and development for new products",
    items: [
      {
        title: "Senior Engineers (3)",
        category: "Engineering",
        type: "cost",
        value: 45000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Product Manager",
        category: "Engineering",
        type: "cost",
        value: 14000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "R&D Tools & Licenses",
        category: "Operations",
        type: "cost",
        value: 5000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Future Product Revenue",
        category: "Sales",
        type: "revenue",
        value: 0,
        frequency: "monthly",
        startsAt: nowIndex,
        endsAt: 6,
      },
    ],
  },
  {
    id: "9",
    title: "Cost Optimization Initiative",
    description: "Reduce operational costs through efficiency improvements",
    items: [
      {
        title: "Process Automation",
        category: "Operations",
        type: "cost",
        value: 50000,
        frequency: "one_time",
        startsAt: nowIndex,
      },
      {
        title: "Vendor Negotiation Savings",
        category: "Operations",
        type: "revenue",
        value: 15000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Infrastructure Optimization",
        category: "Infrastructure",
        type: "cost",
        value: 20000,
        frequency: "one_time",
        startsAt: nowIndex,
      },
      {
        title: "Monthly Savings",
        category: "Operations",
        type: "revenue",
        value: 8000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
    ],
  },
  {
    id: "10",
    title: "Partnership & Channel Sales",
    description: "Build partner ecosystem for indirect revenue",
    items: [
      {
        title: "Partnership Manager",
        category: "Sales",
        type: "cost",
        value: 12000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Partner Enablement",
        category: "Operations",
        type: "cost",
        value: 15000,
        frequency: "one_time",
        startsAt: nowIndex,
      },
      {
        title: "Partner Commissions",
        category: "Sales",
        type: "cost",
        value: 25000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Channel Revenue",
        category: "Sales",
        type: "revenue",
        value: 100000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
    ],
  },
  {
    id: "11",
    title: "Annual Planning & Budget",
    description: "Yearly budget cycle with strategic investments",
    items: [
      {
        title: "Annual Bonus Pool",
        category: "Operations",
        type: "cost",
        value: 200000,
        frequency: "yearly",
        startsAt: nowIndex,
      },
      {
        title: "Annual Marketing Budget",
        category: "Marketing",
        type: "cost",
        value: 500000,
        frequency: "yearly",
        startsAt: nowIndex,
      },
      {
        title: "Annual Revenue Target",
        category: "Sales",
        type: "revenue",
        value: 5000000,
        frequency: "yearly",
        startsAt: nowIndex,
      },
      {
        title: "Annual Infrastructure",
        category: "Infrastructure",
        type: "cost",
        value: 100000,
        frequency: "yearly",
        startsAt: nowIndex,
      },
    ],
  },
  {
    id: "12",
    title: "Acquisition Integration",
    description: "Post-acquisition integration costs and synergies",
    items: [
      {
        title: "Integration Team",
        category: "Operations",
        type: "cost",
        value: 40000,
        frequency: "monthly",
        startsAt: nowIndex,
        endsAt: 3,
      },
      {
        title: "Integration Costs",
        category: "Operations",
        type: "cost",
        value: 200000,
        frequency: "one_time",
        startsAt: nowIndex,
      },
      {
        title: "Acquired Revenue",
        category: "Sales",
        type: "revenue",
        value: 250000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
      {
        title: "Cost Synergies",
        category: "Operations",
        type: "revenue",
        value: 50000,
        frequency: "monthly",
        startsAt: nowIndex,
      },
    ],
  },
];

// Individual item templates for modals
export type ItemTemplate = {
  id: string;
  title: string;
  category: string;
  value: number;
  frequency: "monthly" | "one_time" | "yearly";
  description: string;
};

export const REVENUE_ITEM_TEMPLATES: ItemTemplate[] = [
  {
    id: "mrr",
    title: "Monthly Recurring Revenue",
    category: "Subscription",
    value: 10000,
    frequency: "monthly",
    description: "SaaS subscriptions, memberships",
  },
  {
    id: "arr",
    title: "Annual Contract",
    category: "Subscription",
    value: 50000,
    frequency: "yearly",
    description: "Annual software licenses",
  },
  {
    id: "funding-seed",
    title: "Seed Funding",
    category: "Funding",
    value: 500000,
    frequency: "one_time",
    description: "Seed investment round",
  },
  {
    id: "funding-series-a",
    title: "Series A Funding",
    category: "Funding",
    value: 3000000,
    frequency: "one_time",
    description: "Series A investment round",
  },
  {
    id: "enterprise-deal",
    title: "Enterprise Deal",
    category: "Sales",
    value: 100000,
    frequency: "one_time",
    description: "Large one-time contract",
  },
  {
    id: "consulting",
    title: "Consulting Revenue",
    category: "Services",
    value: 15000,
    frequency: "monthly",
    description: "Professional services, consulting",
  },
  {
    id: "grant",
    title: "Grant / Award",
    category: "Funding",
    value: 25000,
    frequency: "one_time",
    description: "Government grants, awards",
  },
  {
    id: "upsell",
    title: "Upsell Revenue",
    category: "Sales",
    value: 5000,
    frequency: "monthly",
    description: "Expansion revenue from existing customers",
  },
];

export const COST_ITEM_TEMPLATES: ItemTemplate[] = [
  {
    id: "engineer",
    title: "Software Engineer",
    category: "Engineering",
    value: 12500,
    frequency: "monthly",
    description: "Full-time engineer salary",
  },
  {
    id: "senior-engineer",
    title: "Senior Engineer",
    category: "Engineering",
    value: 16000,
    frequency: "monthly",
    description: "Senior/Staff level engineer",
  },
  {
    id: "product-manager",
    title: "Product Manager",
    category: "Engineering",
    value: 14000,
    frequency: "monthly",
    description: "Product management role",
  },
  {
    id: "designer",
    title: "Designer",
    category: "Engineering",
    value: 10000,
    frequency: "monthly",
    description: "Product/UX designer",
  },
  {
    id: "sales-rep",
    title: "Sales Representative",
    category: "Sales",
    value: 10000,
    frequency: "monthly",
    description: "Sales rep base salary",
  },
  {
    id: "sales-commission",
    title: "Sales Commission",
    category: "Sales",
    value: 5000,
    frequency: "monthly",
    description: "Variable sales compensation",
  },
  {
    id: "marketing-budget",
    title: "Marketing Budget",
    category: "Marketing",
    value: 15000,
    frequency: "monthly",
    description: "Paid ads, content, events",
  },
  {
    id: "cloud-infra",
    title: "Cloud Infrastructure",
    category: "Infrastructure",
    value: 5000,
    frequency: "monthly",
    description: "AWS, GCP, Azure costs",
  },
  {
    id: "office-rent",
    title: "Office Rent",
    category: "Operations",
    value: 8000,
    frequency: "monthly",
    description: "Monthly office lease",
  },
  {
    id: "software-tools",
    title: "Software Tools",
    category: "Operations",
    value: 2000,
    frequency: "monthly",
    description: "SaaS subscriptions, dev tools",
  },
  {
    id: "legal-accounting",
    title: "Legal & Accounting",
    category: "Operations",
    value: 3000,
    frequency: "monthly",
    description: "Professional services",
  },
  {
    id: "equipment",
    title: "Equipment Purchase",
    category: "Infrastructure",
    value: 50000,
    frequency: "one_time",
    description: "Laptops, monitors, furniture",
  },
];
